### ISSUE TITLE
Decide Website layout

### ISSUE THREAD

**Issue by drashti4** [drashti4/localisationofschool#1]
Planning for rough website layout and one logo for this project

**Comment by drashti4** [comment]
Rough Layout https://drive.google.com/open?id=0BzyFOR0gG5_9T25RTW5rcnNhZkk

**Comment by Baratang** [comment]
How far are you with the Layout?

**Comment by Baratang** [comment]
Do you have a Logo and Project Name?

**Comment by drashti4** [comment]
I don't have logo but Project name will be same "localisation for school"

**Comment by Baratang** [comment]
Thats too long.

**Comment by Baratang** [comment]
for marketing purposes that is not appealing :)

**Comment by Baratang** [comment]
EG - Whatsapp - is a messaging app, but they call it WhatsApp instead of messaging app

**Comment by Baratang** [comment]
WebLocal :)

**Comment by Baratang** [comment]
LocalWeb

**Comment by Baratang** [comment]
The web layout, How far are you with the Template?

**Comment by Baratang** [comment]
You only have one week

**Comment by drashti4** [comment]
By next Friday web layout will be ready. As per discussion in meeting final name is "Local-Web" :1st_place_medal:

**Comment by DennisDaddy** [comment]
Are you done with planning the rough website layout??
Am interested  in playing a big role in designing the website

**Comment by risbansal** [comment]
I am also interested in helping in website design and making.
Please help me how I can start helping.

**Comment by drashti4** [comment]
Yes, For sprint demo we've website [https://drashti4.github.io/local-web/](url). If we can moderate it at some extra ordinary level. Then Let's start :muscle:

**Comment by drashti4** [comment]
Leave your comment here Or join [https://gitter.im/Open-Leadership-Localisation-of-School/Lobby](url)

**Comment by DennisDaddy** [comment]
This sprint demo website link  is  not available https://drashti4.github.io/local-web/. (page not found)

**Comment by risbansal** [comment]
Try this one  @DennisDaddy  https://github.com/drashti4/local-web

**Comment by cbaba20** [comment]
Not able to join gitter channel

**Comment by drashti4** [comment]
@cbaba20 Join here https://gitter.im/Open-Leadership-Localisation-of-School
