### ISSUE TITLE
What We Do Part

### ISSUE THREAD

**Issue by drashti4** [drashti4/localisationofschool#11]
Suggest 3 short line on which we working on. Right now this is what comes in my mind 

- Localisation
- Web Literacy
- Community Building (This is long term goal)

**Comment by drashti4** [comment]
1) Web Literacy & l10n  - This will redirect to mozilla web literacy website.
2) Women in web - WIP
3) Community Building

**Comment by aspee** [comment]
![d](https://user-images.githubusercontent.com/1244052/27433746-9810dce4-5773-11e7-9309-85ab44b21568.png)

A quick suggestion for icon

**Comment by aspee** [comment]
or this
![d1](https://user-images.githubusercontent.com/1244052/27434140-3f9d03ce-5775-11e7-8278-8ba25d37e71e.png)

**Comment by drashti4** [comment]
left to change icon
