### ISSUE TITLE
Layout for Women In Web Section

### ISSUE THREAD

**Issue by drashti4** [drashti4/localisationofschool#18]
In this we'll localise resources especially for women. such as articles or any blog post which will encourage them to participate on web. In this translator can submit localise file for uploaded article.

How this section will look like? Any idea, suggestion?
related issue #11

**Comment by aspee** [comment]
Suggested Icon
![d1](https://user-images.githubusercontent.com/1244052/27434192-7be8937a-5775-11e7-98ec-0bc72061bd28.png)

**Comment by aspee** [comment]
![d1100](https://user-images.githubusercontent.com/1244052/27437483-00cb6f4a-5780-11e7-8606-78b4c9d3e883.png)

**Comment by aspee** [comment]
![adv](https://user-images.githubusercontent.com/1244052/27438261-494177cc-5782-11e7-8d43-83798648d5b6.png)

**Comment by aspee** [comment]
![adv10](https://user-images.githubusercontent.com/1244052/27438519-20c1cad0-5783-11e7-9fe2-05a3920633f6.png)

**Comment by drashti4** [comment]
Amazing work @aspee :raised_hands: Really appreciate your efforts! :+1: Last second will be more relative to our project. My vote goes to that. @cbaba20 @amirad would love if you can share your views on this.

**Comment by amirad** [comment]
Ohh these are fun! And beautiful illustration of the woman. I find it slightly odd to have anything come out of her head but overall, do like the second last one the best as well.

**Comment by kitsunenosaraT** [comment]
Greetings! My name is Sara, from Italy. I took part in the Open Leadership training in the same cohort of @drashti4
My project is a [open source localization guide](https://github.com/kitsunenosaraT/Mozilla-Italia-l10n-guide) for volunteer communities. Because of this I took interest in your *Localisation of school* and would like to help you out.

In the last Open Leadership Call Drashti said you were looking for localization tools.
I snooped around your repo a bit and, if I understood correctly, you are looking for a web space where to:
- host articles and didactic material
- allow others to localize existing material or upload new.

If that's the case, I think the best alternative would be a [wiki-based platform](https://en.wikipedia.org/wiki/Comparison_of_wiki_hosting_services) such as [MDN](https://developer.mozilla.org).
The advantages are:
- easily editable by any registered user
- multilingual support: easily localize a page in various languages
- several free hosting alternatives
- wiki-format is pretty well known and many people already knows how to use it.

Also, when localizing, translation quality is very important, especially for a project like yours that aims to teach young students.
Ideally, each translation should be reviewed by another native speaker, but this will not be always possible.
Yet, it would be useful to adopt a **style guide** to teach contributors about the basics of localization.
I hope this short document will give you some ideas:[Translation Best Practices](https://github.com/kitsunenosaraT/Mozilla-Italia-l10n-guide/blob/master/en/1-Translation_Best_Practices.md)

Finally, many people tend to start localizing an article and then just leave it half done. This is something to avoid because incomplete documentation just confuses the reader.
So, another suggestion I want to share is to write a short set of rules on the localization process, like a **Code of Conduct** to inform contributors on how to behave and what level of commitment is required. This is a [localization-specific code of conduct](https://github.com/kitsunenosaraT/Mozilla-Italia-l10n-guide/blob/master/CODE_OF_CONDUCT.md#mozilla-italia-l10n-team-participation-guidelines) me and my teammates devised. If it helps, please feel free to draw inspiration from it!

If you have some specific needs or questions, just ask me and I will try to support you as best as I can!

p.s. @aspee  Those icons look wonderful! My favourite is the third one 😊

**Comment by drashti4** [comment]
Its useful :+1: Thanks @kitsunenosaraT for sharing it with us. I gone through that link and CoC for localization is quite good. Also, If we use wiki-based service, Do we need redirect use to that site?

**Comment by kitsunenosaraT** [comment]
Glad I could be of any help 😁 
You have quite a beautiful site, it would be a pity to abandon it.
I would suggest to leave https://drashti4.github.io/localisationofschool/ as a front page, then link to the wiki for the actual content/articles.

The benefit in the long run is that people will be able to localize content directly without a submission process. It is less work for you, but above all encourages people to participate.
I know for experience that the more complex a submission process is (i.e. having to contact an unknown person, waiting for their reply etc.) the less likely are people to contribute.

**Comment by drashti4** [comment]
@kitsunenosaraT something big :smile_cat: Yes but we can do this for localising resources only. We also have [how to start tab](https://drashti4.github.io/localisationofschool/lessons/) 

Currently it is under progress. There will be language like English, Hindi, Italian instead of python, git and R. It will be n number of languages. Each language will have 5 module, In each 5 module there will be 6-7 videos. When someone click on that video, one lesson tab will appear [like this](https://drashti4.github.io/localisationofschool/lessons/Module-I/biopython/lesson/) there will be subscript link. People will localise that subscript.

 Hope this make sense. How will this fit in wiki service? I am quite newbie to this. If you have any doubt in above information, Let me know.

**Comment by kitsunenosaraT** [comment]
I see you're already quite organized :grin:
Currently you host videos on Youtube and then embed them in the website, right? That's a good choice, I think. It also has a sleek subtitling function.

For the Women in Web (static articles) things are simpler, but, as you say, putting videos in wikis may become needlessy complicated :thinking: 

Are you perhaps familiar with [Khan Academy](https://www.khanacademy.org)? They are doing something very similar to your project in localizing videos in all languages.
Maybe it's worth to look how they are organized to get inspiration.

Have a look at [this FAQs](https://khanacademy.zendesk.com/hc/en-us/categories/200186020-Translators). As you can read, they use [CrowdIn](https://crowdin.com/) translation platform for the various content and also have a [guide for dubbing videos](https://khanacademy.zendesk.com/hc/en-us/sections/205873648-Dubbing-and-Recreating-Videos) and another for [subtitling](https://khanacademy.zendesk.com/hc/en-us/articles/226430248-What-are-the-quality-guidelines-for-creating-subtitles-).

An open source alternative to CrowdIn would be [Pootle](http://pootle.translatehouse.org/). Once upon a time Mozilla used a modified version of Pootle for localization, and it worked pretty well.

**Comment by drashti4** [comment]
It's very useful :smiley: Sorry for late reply, We have heavy rain here and no connectivity.

I was following Khan academy for layout designing, but didn't aware of this. Thank you very much for sharing. Only different between Khan academy and our project is we are localising resources specifically for web literacy. 

Also, I tried to setup pootle but facing some error, will resolve it in short time. Have you setup that?
 or any kind of experience with pootle server @kitsunenosaraT 

**If pootle work well for us then...**

We can new project in pootle for each article (or resources which we want to localise) and from website we need to redirect users to pootle project. But do I need domain for pootle? :confused:

**Comment by kitsunenosaraT** [comment]
Oh, rainy season? I see ☔️ 
Unfortunately I never personally set up Pootle, I always used it strictly from client side as a translator (i.e. input my credentials and start translating from the web interface.)

However I don't think you need a to set up another domain for hosting translations on Pootle.
At least, in Mozilla, we simply host the files on a [GitHub repo](https://github.com/mozilla-l10n/) (before that we used [SVN](https://subversion.apache.org/) ).

I'm sorry I'm not knowledgeable enough to help you with the setup, but at least I can redirect you towards the documentation on setting up [Mozilla's own version of Pootle](https://wiki.mozilla.org/Verbatim) -- [Repo](https://github.com/mozilla/verbatim).
I sincerely hope it helps. If still have any doubts, I may try and get in contact with someone in Mozilla that knows how to manage this things.

**Comment by drashti4** [comment]
After building website for this project this is second major thing we're working on 😺 Thank you @kitsunenosaraT It seems bit long process for setting up server in my machine. 

 What else need for this section 💭 
 **layout for articles** [like this](https://mozillafestival.org/projects) If user click on visit button it will redirect to details of article and from there, to pootle.

but, any idea on how will we display articles in different languages in this section 🤔 
suggestions are welcome 😃

**Comment by drashti4** [comment]
It is in development phase now. you can check on [website](https://drashti4.github.io/localisationofschool/wow-resources/) where we will have articles regarding web literacy in different language. Article will be two type 
- sharing personal experience i.e if event done by you or your personal story.
- Informative article which encourage women to participate on web.

Let me know ladies! If you willing to share your story in your language. @kitsunenosaraT @amirad

**Comment by amirad** [comment]
Ohh I see many of my pictures up on that site! 

Tell me more about what type of story you are looking for? Do you want a link to a story written on a specific site or you want the content straight on your site? I can share links like this: https://medium.com/athena-talks/women-need-to-take-more-steps-to-protect-themselves-in-digital-spaces-20b8a3877b7c or send something else

**Comment by drashti4** [comment]
Hi amira! I am looking for story which is indecent based. For example gender bias you've faced, hurdles you faced for not getting in more women in web (not taking risk, fear to talk with new people, discourage by others). Anything you noticed in public event which is barrier for participating on web for women.

I noticed language as barrier [check this post](https://medium.com/@drashtipandya1/teach-the-web-with-housewives-e8043e28400b) You can write in draft and send on drashtipandya37@gmail.com I'll publish on my site or you can directly share your blog link.

I love your blog post and specially activity you did on women safety. Planning to localise it :+1:

**Comment by kitsunenosaraT** [comment]
Hi Drashti! I'm so sorry it took me long enough to reply... 😢 
I would be very honored to write an article for Women on web!

By the way, about localization...
I feel none of the solutions I mentioned above are very practical for the way your site is built.
But recently I found out this Git-Hub based site: [Activate Mozilla](https://activate.mozilla.community/). Repo: https://github.com/mozilla/activate.mozilla.community
Basically, they took advantage of GitHub inbuilt functions to manage different locales for the same site. Each locale has its own subfolder with copies of the localizable content, that the localization team can translate through GitHub.
Have a look at the [README](https://github.com/mozilla/activate.mozilla.community/blob/gh-pages/README.md), a [issue requesting a new locale](https://github.com/mozilla/activate.mozilla.community/issues/25) and the following post in [issue 34](https://github.com/mozilla/activate.mozilla.community/issues/34):
> MichaelKohler commented on 16 Aug 2016 

>@a-kilroy thanks for jumping in, let me try to answer your question. 
>For the activate.mozilla.community website, we're using this  repository here, which also includes all texts that are displayed on the  page.
>The English, original source files, are located in the _pages  folder directly:
> https://github.com/mozilla/activate.mozilla.community/tree/gh-pages/_pages
>For every localization there are the following steps to do:
>Create a subfolder in the _pages which indicates the locale, for example "es" like it already exists: 
>https://github.com/mozilla/activate.mozilla.community/tree/gh-pages/_pages/es 
>Then you need to copy all the English folders and Markdown documents  to this and start translating them, so in the end we have one complete  file in EN, one complete file in ES Create a file for the general GUI specific translations:
> https://github.com/mozilla/activate.mozilla.community/blob/gh-pages/_data/l10n/es.yml, which also specifies the URL for the langues, like /es/ for Spanish 
>Add your locale to the Language switch 
>[...]

Mind you, it's not exactly intuitive (especially for the translator, who needs to know how to handle markdown files), but I guess it could be an option.

**Comment by drashti4** [comment]
That is interesting. I read all comments. Although we are not able to take support from pontoon we have two option either use Jekyll plugin for handling different language or use i18n library. I like their structure of repo for handling local. Will apply that :) 

Regarding to article can you share your experience or any incident on gender bias or where you think this is hurdle for you/other-women for getting into web. It would be better if it will be in Italian and English :smile: Thank you for referring issue, It was really helpful.
