### ISSUE TITLE
Requirement Gathering for Website

### ISSUE THREAD

**Issue by drashti4** [drashti4/localisationofschool#2]
**1. Give voice to localise -**  Contribution guideline how to add your audio to existing video. 

**2. Search By Language Feature -** If User enter language He will get all videos in that language.

**3. Search Contributor By Language Feature -** If User enter language He will Contributor list in that language.So that he can connect with local contributor.

**4. Modules -** We will have total 5 Modules in each languages. Each Modules will have 5-6 Videos. And at the end of each video we will have 1 Activity/Assignment.

**5. Feedback/Comment Session -** After ending each video & activity, There will be a comment or feedback section. 

**6. Show Current Status -** These many Modules (Count of Module) are available in **n** languages.
                                              We are currently working on **n** languages on **n** number of Module.

**7. Other Resources Section -** Where people can submit other resources in local language. It will add a curated list of options for people.

**Comment by Baratang** [comment]
The project is about
 
Localization of web literacy content with a goal of creating an accessible place for school kids to be educated in their local language.  The organization will produces short lectures in the form of YouTube videos in localized Indian language for teachers and parents to understand it as a start, with a vision to encourage and teach other people to contribute and localize their web literacy.  The website will also include supplementary practice exercises and tools for educators. All resources will be open source and available to users of the website. The website and its content will be provided mainly in Indian dialect, but contributors are also encouraged to localize content in their local languages like Setswana from Botswana.

**Comment by Baratang** [comment]
Lets focus on achieving the basics of your goal. 
 1. Two modules ( each with 8 videos). 
 2. Have a layout the Website to host video (content).

How do you make sure that the modules are hosted on the website.

**Comment by Baratang** [comment]
During Sprint - Contributors will be of two type:
 1. Technical-Help to build and maintain website
 2. Animated Video Creators - Put audio for localized video.
 3. 
After Sprint you can then focus on 
 3. Non- technical - Reaching to school for web literacy campaign

**Comment by stephwright** [comment]
Could you also have some non-technical aspects for folks to work on during the Sprint? Like creating documentation in the repo (e.g. adding more detail to CONTRIBUTING.md) or moving the web template info to markdown instead of being in images?

**Comment by drashti4** [comment]
@stephwright Agree! We need to polished CONTRIBUTING.md. During sprint we are looking for people who are interested in documentation and especially in technical writing for making notes of videos.

I am looking for response from wrangler on sprint issue.

**Comment by andreabedini** [comment]
hi there, I strongly recommend putting the videos on any video hosting service (does Mozilla have one?). Embedding the videos in the website is very easy compared to hosting the videos yourself. From the technical point of view, any hosting service would do (Youtube?), but some one has to make a decision and upload the videos. My 2c, happy mozsprinting!

**Comment by drashti4** [comment]
@andreabedini Yes, Right now I have put 2-3 videos on my channel and embedded it in prototype type website. drashti4.github.io/local-web/

**Comment by amirad** [comment]
@drashti4 can we integrate a 'other resources section' where people can submit other resources in that local language? It will add a curated list of options for people.

**Comment by drashti4** [comment]
@amirad This is awesome. I have updated the issue.
