### ISSUE TITLE
Create Logo

### ISSUE THREAD

**Issue by drashti4** [drashti4/localisationofschool#5]
Idea about logo - It will display different type of people who wears traditional dress are connected to internet. Any suggestions are welcome.

**Comment by drashti4** [comment]
![logo_1495356592283 1](https://cloud.githubusercontent.com/assets/9081004/26282875/e10943d2-3e37-11e7-8e29-866459190dff.png)

**Comment by drashti4** [comment]
![finallogo](https://cloud.githubusercontent.com/assets/9081004/26282878/026dc00c-3e38-11e7-8b37-f2d9c03319dd.jpg)

**Comment by aspee** [comment]
Wow Drashti! Looks cool!
Even I have created one logo. Will be uploading soon. 😊

**Comment by drashti4** [comment]
Cool! I am assigning this to you. :+1:

**Comment by aspee** [comment]
![logo_1495364041601](https://cloud.githubusercontent.com/assets/1244052/26284108/428ae7be-3e51-11e7-9635-c6ed5a5b951a.png)

**Comment by aspee** [comment]
![logo_1495364314801](https://cloud.githubusercontent.com/assets/1244052/26284112/51d35ba2-3e51-11e7-992d-e7cc67a7ac7f.png)

**Comment by drashti4** [comment]
This looks awesome <3 Its like connecting the isolated part.

**Comment by drashti4** [comment]
Hey @aspee Can you make Local Web in Bold. It will looks good stickers. What do you think?

**Comment by Baratang** [comment]
I like the first one. It has the infinity element of how far the project reach can go.

**Comment by drashti4** [comment]
Thank you @aspee for your input. We will decide final logo in today's meeting. Would love to see you at call. Ping in telegram @drashti4

**Comment by amirad** [comment]
Did you decide the final logo? These all have good elements?

**Comment by drashti4** [comment]
@amirad No still not have finalise logo. I think the one @aspee created need font change to bold. Share your views also :smile:

**Comment by Jaythageek** [comment]
![logon](https://cloud.githubusercontent.com/assets/25347935/26726509/06e7e5d6-47ac-11e7-8779-fce62943d2ec.png)

**Comment by Jaythageek** [comment]
what do you think

**Comment by amirad** [comment]
So many good concepts. These can all be applicable. I think my favourite is https://cloud.githubusercontent.com/assets/1244052/26284108/428ae7be-3e51-11e7-9635-c6ed5a5b951a.png

**Comment by cbaba20** [comment]
My vote goes for what @amirad has shared . it looks good actually .

**Comment by drashti4** [comment]
thanks for your input @Jaythageek You did awesome job :dancing_men: I like the last one and the one Amira suggested.

**Comment by learneradarsh** [comment]
![image](https://cloud.githubusercontent.com/assets/18267421/26738011/211ffb6c-47ea-11e7-96d8-0e0d914e253f.png)

**Comment by learneradarsh** [comment]
![image](https://cloud.githubusercontent.com/assets/18267421/26738076/61400ff2-47ea-11e7-9b14-29ba6d03b979.png)

**Comment by learneradarsh** [comment]
![image](https://cloud.githubusercontent.com/assets/18267421/26738136/9d83510e-47ea-11e7-9da1-40312bbcc162.png)

**Comment by learneradarsh** [comment]
![image](https://cloud.githubusercontent.com/assets/18267421/26738210/e486934a-47ea-11e7-8574-7b485aeb1e53.png)

**Comment by learneradarsh** [comment]
![image](https://cloud.githubusercontent.com/assets/18267421/26738256/0c40e4da-47eb-11e7-9036-c9b8badd6df0.png)

**Comment by drashti4** [comment]
whooho! :1234: That's pretty awesome. Thank you @learneradarsh :+1:

**Comment by learneradarsh** [comment]
Have you opted anyone?

**Comment by drashti4** [comment]
First with video sign and last with tree icon seems good. :+1: I don't think so this tag line suits our project :octocat: Let's decide tagline by tomorrow or in short time else with no tagline we'll final logo. @learneradarsh @amirad

**Comment by drashti4** [comment]
Final Selection of Logo
![colobalancetransperant](https://user-images.githubusercontent.com/9081004/27000659-c5ac2526-4dd4-11e7-8733-3415cdcf49ca.png)

**Comment by drashti4** [comment]
![local-web](https://user-images.githubusercontent.com/9081004/27013086-890dae2e-4efa-11e7-8402-3588533905fb.png)
