### ISSUE TITLE
Create Contribution Guide for Editing Video

### ISSUE THREAD

**Issue by drashti4** [drashti4/localisationofschool#6]
Explain how to edit put recorded audio to video.By using openshot or any other Opensource software.

**Comment by amirad** [comment]
@drashti4 can you explain this to me? You want to edit a video? Or add audio to a video?

**Comment by drashti4** [comment]
@amirad It is optional If you want to put subtitle or not. I added different file for subitle in English Language.  It would be easier to translate. 

I have tried with Openshot, Only one thing need to fix otherwise it works like charm :dancer: In that we can do it offline.

**Comment by amirad** [comment]
ooo offline would be wonderful. But if you give people the option to do it with text and openshot than I think you are fine. Those seem like easy enough options to follow.

**Comment by drashti4** [comment]
In Openshot we can do both. **Adding Subtitle and adding audio.** But I am looking for at least two option so In some case Openshot doesn't work, Contributor can do task in other tool also.

One problem currently facing, Uploading video on youtube would be fine or any better option there. I am asking for [this](https://drashti4.github.io/local-web/lessons/python/biopython/lesson/)

**Comment by drashti4** [comment]
[here](https://github.com/drashti4/localisationofschool/blob/gh-pages/LOCALIZE_VIDEO_GUIDE.md) it is. I have used openshot and tried these steps, It is working. In enhancement we are looking forward for creating video demo for same.
