### ISSUE TITLE
Need Header Image for our website 

### ISSUE THREAD

**Issue by cbaba20** [drashti4/localisationofschool#8]
specifications for the new image :  
width: 640px
height: 390px

It should reflect what our website is for . 

I have seen some images which can be fit for our project ,but if required showcase yourself.

If queries then comment in.  

Required : @aspee @aadarsh.

**Comment by cbaba20** [comment]
- ![header1](https://cloud.githubusercontent.com/assets/8758288/26750888/2477b5ec-484a-11e7-86e9-21a5b0ac680f.png)

- ![header1](https://cloud.githubusercontent.com/assets/8758288/26750890/29b52d46-484a-11e7-8a36-d82ef8e68bc9.jpg)

**Comment by drashti4** [comment]
@cbaba20 Looks awesome. :cool:  Have you created this? Is this under opensource licence?

**Comment by cbaba20** [comment]
- ![localization](https://cloud.githubusercontent.com/assets/8758288/26750906/a793ca56-484a-11e7-8fde-1dba1e2acc8a.PNG)

Since we are localizing teaching kits in local languages , so you can keep this kind of symbol while creating graphics for header .

**Comment by cbaba20** [comment]
@drashti4 No, I haven't created it , and I think these designs are close-sourced. so better if we can come up with own one.

**Comment by drashti4** [comment]
@cbaba20 and the last one is also under close-sourced? Translation and localisation?

**Comment by cbaba20** [comment]
This is too, its from my workplace.

**Comment by cbaba20** [comment]
Hello team,
Check this graphics that i have made for header of our project and share your views :
![helloweb 5](https://cloud.githubusercontent.com/assets/8758288/26753378/8253a7e2-4882-11e7-8b1f-d604891a529f.png)

**Comment by drashti4** [comment]
It looks awesome. :100: Only one thing that this poster will be like representing Indian project. We have to represent global. Can we select other famous language in Mozilla l10n like French, German or Dutch.

**Comment by cbaba20** [comment]
Thanks for Your Comment. Here is changed version of poster: 

- ![helloweb 6](https://cloud.githubusercontent.com/assets/8758288/26755538/c062fcc0-48ac-11e7-9eca-9e4661c4a88e.png)
Let me Know if this looks good.

**Comment by drashti4** [comment]
Looks good :+1: Have you put that in header and checked how it looks? So that according to CSS we can modify it.

**Comment by cbaba20** [comment]
Hey Team Checkout the header image after some changes : [1] This is original Image : ![helloweb 12](https://cloud.githubusercontent.com/assets/8758288/26759698/675c8ffc-4923-11e7-850f-6886b9457553.png)

This is how it looks after putting in header and running it :
![screenshot 6](https://cloud.githubusercontent.com/assets/8758288/26759717/0e598ab2-4924-11e7-9c9b-c396d0580310.png)

**Comment by drashti4** [comment]
This header image looking good. We nee to change CSS. I am closing this issue as we completed this task :clinking_glasses: @cbaba20

**Comment by drashti4** [comment]
![header](https://user-images.githubusercontent.com/9081004/27013074-606a3ba4-4efa-11e7-9e58-15407052ffcf.png)
